# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.edge.service import Service
from webdriver_manager.microsoft import EdgeChromiumDriverManager

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Edge(service=Service(EdgeChromiumDriverManager().install()))
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

  def test_registration(self):
    self.driver.get("https://tristula.ga/")
    self.driver.set_window_size(1936, 1096)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) > svg").click()
    self.driver.find_element(By.LINK_TEXT, "Зарегестрируйтесь").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("test3")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("test3@mail.ru")
    self.driver.find_element(By.ID, "id_password1").click()
    self.driver.find_element(By.ID, "id_password1").send_keys("Test3123456")
    self.driver.find_element(By.ID, "id_password2").click()
    self.driver.find_element(By.ID, "id_password2").send_keys("Test3123456")
    self.driver.find_element(By.CSS_SELECTOR, ".text-white").click()
  
  def test_login(self):
    self.driver.get("https://tristula.ga/")
    self.driver.set_window_size(1936, 1096)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) > svg").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("test3")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Test3123456")
    self.driver.find_element(By.CSS_SELECTOR, ".text-white").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) > svg").click()

  def test_profile(self):
    self.test_login()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) > svg").click()

  def test_change_profile(self):
    self.test_profile()
    self.driver.find_element(By.ID, "detailsBtn").click()
    self.driver.find_element(By.ID, "id_first_name").click()
    self.driver.find_element(By.ID, "id_first_name").send_keys("Andrey")
    self.driver.find_element(By.ID, "id_last_name").click()
    self.driver.find_element(By.ID, "id_last_name").send_keys("Ilin")
    self.driver.find_element(By.ID, "id_middle_name").click()
    self.driver.find_element(By.ID, "id_middle_name").send_keys("Yurievich")
    self.driver.find_element(By.ID, "id_phone_number").click()
    self.driver.find_element(By.ID, "id_phone_number").send_keys("85674896756")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(9) .text-white").click()
    self.driver.find_element(By.ID, "addressBtn").click()
    self.driver.find_element(By.ID, "id_city").click()
    self.driver.find_element(By.ID, "id_city").send_keys("Москва")
    self.driver.find_element(By.ID, "addressForm").click()
    self.driver.find_element(By.ID, "id_street").click()
    self.driver.find_element(By.ID, "id_street").send_keys("Ппроп")
    self.driver.find_element(By.ID, "id_house").click()
    self.driver.find_element(By.ID, "id_house").send_keys("45")
    self.driver.find_element(By.ID, "id_housing").click()
    self.driver.find_element(By.ID, "id_housing").send_keys("2")
    self.driver.find_element(By.ID, "id_apartment").click()
    self.driver.find_element(By.ID, "id_apartment").send_keys("4")
    self.driver.find_element(By.ID, "id_intercom_code").click()
    self.driver.find_element(By.ID, "id_intercom_code").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(13) .text-white").click()
    self.driver.find_element(By.ID, "cardBtn").click()
    self.driver.find_element(By.ID, "id_card_number").click()
    self.driver.find_element(By.ID, "id_card_number").send_keys("12345678910")
    self.driver.find_element(By.ID, "id_expiry_date").click()
    self.driver.find_element(By.ID, "id_expiry_date").send_keys("2345")
    self.driver.find_element(By.ID, "id_card_number").click()
    self.driver.find_element(By.ID, "id_card_number").send_keys("1234567891012345")
    self.driver.find_element(By.ID, "id_cvc_code").click()
    self.driver.find_element(By.ID, "id_cvc_code").send_keys("234")
    self.driver.find_element(By.ID, "id_expiry_date").click()
    self.driver.find_element(By.ID, "id_expiry_date").click()
    self.driver.find_element(By.ID, "id_expiry_date").send_keys("23/45")
    self.driver.find_element(By.CSS_SELECTOR, "#cardForm .text-white").click()
    self.driver.find_element(By.ID, "passwordBtn").click()
    self.driver.find_element(By.ID, "passwordBtn").click()

  def test_order(self):
    self.test_login()
    self.driver.find_element(By.LINK_TEXT, "Каталог").click()
    self.driver.find_element(By.LINK_TEXT, "Тумбы").click()
    self.driver.find_element(By.CSS_SELECTOR, "#splide01-slide03 .mx-auto").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-white").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icons .inline:nth-child(1)").click()
    self.driver.find_element(By.ID, "id_expiry_date").click()
    self.driver.find_element(By.ID, "id_expiry_date").send_keys("23/45")
    self.driver.find_element(By.ID, "id_cvc_code").click()
    self.driver.find_element(By.ID, "id_cvc_code").send_keys("345")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-\\[\\#333333\\] > .text-\\[32px\\]").click()

  def test_events(self):
    self.test_login()
    self.driver.find_element(By.LINK_TEXT, "События").click()

  def test_contacts(self):
    self.test_login()
    self.driver.find_element(By.LINK_TEXT, "Контакты").click()

  def test_callback(self):
    self.driver.get("https://tristula.ga/")
    self.driver.set_window_size(1936, 1096)
    self.driver.find_element(By.LINK_TEXT, "Обратная связь").click()
    self.driver.find_element(By.ID, "id_subject").click()
    self.driver.find_element(By.ID, "id_subject").send_keys("Пук")
    self.driver.find_element(By.ID, "id_description").click()
    self.driver.find_element(By.ID, "id_description").send_keys("ПукПук")
    self.driver.find_element(By.CSS_SELECTOR, ".text-white").click()

  def test_admin_login(self):
    self.driver.get("https://tristula.ga/admin")
    self.driver.set_window_size(1936, 1096)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("root")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("aboba123")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()

  def test_addevent(self):
    self.test_admin_login()
    self.driver.find_element(By.CSS_SELECTOR, ".model-event .addlink").click()
    self.driver.find_element(By.ID, "id_event").click()
    self.driver.find_element(By.ID, "id_event").send_keys("Proverka")
    self.driver.find_element(By.NAME, "_save").click()

  def test_admin_feed(self):
    self.test_admin_login()
    self.driver.find_element(By.LINK_TEXT, "Feedbacks").click()
    self.driver.find_element(By.NAME, "_selected_action").click()
    self.driver.find_element(By.NAME, "_selected_action").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_subject").click()
    self.driver.find_element(By.ID, "id_subject").send_keys("Gfhfhf")
    self.driver.find_element(By.ID, "id_description").click()
    self.driver.find_element(By.ID, "id_description").send_keys("Desc")
    self.driver.find_element(By.NAME, "_save").click()

  def test_admin_order_product(self):
    self.test_admin_login()
    self.driver.find_element(By.LINK_TEXT, "Order Products").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_order").click()
    dropdown = self.driver.find_element(By.ID, "id_order")
    dropdown.find_element(By.XPATH, "//option[. = 'Order object (1)']").click()
    self.driver.find_element(By.ID, "id_product").click()
    dropdown = self.driver.find_element(By.ID, "id_product")
    dropdown.find_element(By.XPATH, "//option[. = 'Product object (16)']").click()
    self.driver.find_element(By.ID, "id_quantity").send_keys("1")
    self.driver.find_element(By.ID, "id_quantity").click()
    self.driver.find_element(By.NAME, "_save").click()

  def test_admin_orders(self):
    self.test_admin_login()
    self.driver.find_element(By.LINK_TEXT, "Orders").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_user").click()
    dropdown = self.driver.find_element(By.ID, "id_user")
    dropdown.find_element(By.XPATH, "//option[. = 'test3']").click()
    self.driver.find_element(By.ID, "id_status").click()
    self.driver.find_element(By.ID, "id_status").send_keys("progress")
    self.driver.find_element(By.NAME, "_save").click()

  def test_adminaddaddress(self):
    self.test_admin_login()
    self.driver.find_element(By.LINK_TEXT, "User Addresses").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_user").click()
    dropdown = self.driver.find_element(By.ID, "id_user")
    dropdown.find_element(By.XPATH, "//option[. = 'test2']").click()
    self.driver.find_element(By.ID, "id_city").click()
    self.driver.find_element(By.ID, "id_city").send_keys("Москва")
    self.driver.find_element(By.ID, "id_street").click()
    self.driver.find_element(By.ID, "id_street").send_keys("Красная площадь")
    self.driver.find_element(By.ID, "id_house").click()
    self.driver.find_element(By.ID, "id_house").send_keys("54")
    self.driver.find_element(By.ID, "id_housing").click()
    self.driver.find_element(By.ID, "id_housing").send_keys("2")
    self.driver.find_element(By.ID, "id_apartment").click()
    self.driver.find_element(By.ID, "id_apartment").send_keys("1")
    self.driver.find_element(By.ID, "id_intercom_code").click()
    self.driver.find_element(By.ID, "id_intercom_code").send_keys("32454")
    self.driver.find_element(By.NAME, "_save").click()

  def test_adminuserdetail(self):
    self.test_admin_login()
    self.driver.find_element(By.LINK_TEXT, "User Details").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_user").click()
    dropdown = self.driver.find_element(By.ID, "id_user")
    dropdown.find_element(By.XPATH, "//option[. = 'test2']").click()
    self.driver.find_element(By.ID, "id_first_name").click()
    self.driver.find_element(By.ID, "id_first_name").send_keys("Andrew")
    self.driver.find_element(By.ID, "id_last_name").click()
    self.driver.find_element(By.ID, "id_last_name").send_keys("Ilin")
    self.driver.find_element(By.ID, "id_middle_name").click()
    self.driver.find_element(By.ID, "id_middle_name").send_keys("Yurievich")
    self.driver.find_element(By.ID, "id_phone_number").click()
    self.driver.find_element(By.ID, "id_phone_number").send_keys("89765643454")
    self.driver.find_element(By.NAME, "_save").click()

