-- MySQL Script generated by MySQL Workbench
-- Sun Dec 12 20:35:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ege
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ege
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ege` DEFAULT CHARACTER SET utf8 ;
USE `ege` ;

-- -----------------------------------------------------
-- Table `ege`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ege`.`Students` (
  `St_ID` INT NOT NULL,
  `St_Name` VARCHAR(45) NOT NULL,
  `St_Grade` INT NOT NULL,
  PRIMARY KEY (`St_ID`),
  UNIQUE INDEX `St_ID_UNIQUE` (`St_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ege`.`EType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ege`.`EType` (
  `ET_ID` INT NOT NULL,
  `ET_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ET_ID`),
  UNIQUE INDEX `ET_ID_UNIQUE` (`ET_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ege`.`Schools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ege`.`Schools` (
  `Sc_ID` INT NOT NULL,
  `Sc_Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Sc_ID`),
  UNIQUE INDEX `Sc_ID_UNIQUE` (`Sc_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ege`.`TType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ege`.`TType` (
  `TT_ID` INT NOT NULL,
  `TT_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TT_ID`),
  UNIQUE INDEX `TT_ID_UNIQUE` (`TT_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ege`.`Tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ege`.`Tutor` (
  `T_ID` INT NOT NULL,
  `T_Name` VARCHAR(45) NOT NULL,
  `T_Price` INT NOT NULL,
  `T_Exp_Years` INT NOT NULL,
  `TT_ID` INT NOT NULL,
  PRIMARY KEY (`T_ID`),
  UNIQUE INDEX `T_Name_UNIQUE` (`T_ID` ASC) VISIBLE,
  INDEX `fk_Tutor_TType_idx` (`TT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Tutor_TType`
    FOREIGN KEY (`TT_ID`)
    REFERENCES `ege`.`TType` (`TT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ege`.`SType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ege`.`SType` (
  `ST_ID` INT NOT NULL,
  `ST_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ST_ID`),
  UNIQUE INDEX `ST_ID_UNIQUE` (`ST_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ege`.`Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ege`.`Subjects` (
  `S_ID` INT NOT NULL,
  `S_Name` VARCHAR(45) NOT NULL,
  `T_ID` INT NOT NULL,
  `ST_ID` INT NOT NULL,
  PRIMARY KEY (`S_ID`, `T_ID`),
  UNIQUE INDEX `S_ID_UNIQUE` (`S_ID` ASC) VISIBLE,
  INDEX `fk_Subjects_Tutor1_idx` (`T_ID` ASC) VISIBLE,
  INDEX `fk_Subjects_SType1_idx` (`ST_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Subjects_Tutor1`
    FOREIGN KEY (`T_ID`)
    REFERENCES `ege`.`Tutor` (`T_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_SType1`
    FOREIGN KEY (`ST_ID`)
    REFERENCES `ege`.`SType` (`ST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ege`.`Exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ege`.`Exams` (
  `E_ID` INT NOT NULL,
  `E_Name` VARCHAR(45) NOT NULL,
  `E_Points` INT NOT NULL,
  `E_Date` DATETIME NOT NULL,
  `St_ID` INT NOT NULL,
  `ET_ID` INT NOT NULL,
  `Sc_ID` INT NOT NULL,
  `S_ID` INT NOT NULL,
  `T_ID` INT NOT NULL,
  PRIMARY KEY (`E_ID`, `St_ID`, `ET_ID`, `Sc_ID`, `S_ID`, `T_ID`),
  UNIQUE INDEX `E_ID_UNIQUE` (`E_ID` ASC) VISIBLE,
  INDEX `fk_Exams_Students1_idx` (`St_ID` ASC) VISIBLE,
  INDEX `fk_Exams_EType1_idx` (`ET_ID` ASC) VISIBLE,
  INDEX `fk_Exams_Schools1_idx` (`Sc_ID` ASC) VISIBLE,
  INDEX `fk_Exams_Subjects1_idx` (`S_ID` ASC, `T_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Exams_Students1`
    FOREIGN KEY (`St_ID`)
    REFERENCES `ege`.`Students` (`St_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exams_EType1`
    FOREIGN KEY (`ET_ID`)
    REFERENCES `ege`.`EType` (`ET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exams_Schools1`
    FOREIGN KEY (`Sc_ID`)
    REFERENCES `ege`.`Schools` (`Sc_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exams_Subjects1`
    FOREIGN KEY (`S_ID` , `T_ID`)
    REFERENCES `ege`.`Subjects` (`S_ID` , `T_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
